### PR TITLE
Require Bundler when brew installing avrdude.

### PR DESCRIPTION
**Pull request by alyssais**
I got an error message saying that the Bundler constant had not been initialized. Requiring Bundler seemed to fix the issue. Apologies if there is somewhere else I should have required Bundler; I didn't spend much time looking over the code.

### CODE REVIEW

**Comment by edgarsilva** [comment]
@stewart Hey Andrew, can you do us a favor and confirm this when you have a chance? Thanks.

@penman Thanks for the heads up and the patch!

**Comment by stewart** [comment]
Might be better as:

``` ruby
require 'bundler' unless defined?(Bundler)
```

**Comment by alyssais** [comment]
@stewart updated my pull request.

**Comment by stewart** [comment]
:shipit:

**Pull request merged**
